---
# handlers file for ansible-sshd
- name: "restart ssh"
  service:
    name: "ssh"
    state: "restarted"
  become: true

- name: "restart sshd"
  service:
    name: "sshd"
    state: "restarted"
  become: true
